name: Build and push Docker image to Docker Hub (ARM & AMD)

on:
  push:
    branches: [ "main","development" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push ARM Docker Image
      working-directory: Backend/
      run: |
        docker buildx build \
          --platform=linux/arm64 \
          -t lee112/cronai:arm \
          -f Service/Dockerfile \
          --push .

    - name: Build and Push AMD Docker Image
      working-directory: Backend/
      run: |
        docker buildx build \
          --platform=linux/amd64 \
          -t lee112/cronai:amd \
          -f Service/Dockerfile \
          --push .
